"""Service layer — the single entry point for every interface.

The CLI, the Telegram bot and the future HTTP API all call these functions. They never talk
to the engine or the database directly, which is what keeps the bot and the web from
drifting apart in the details.

Every function takes a session first and **does not commit**: the caller owns the
transaction, so several calls can be composed into one unit of work.
"""

from .accounts import (
    account_for_identity,
    account_for_session,
    attach_identity,
    close_all_sessions,
    close_session,
    ensure_identity,
    get_account,
    issue_sign_in_link,
    open_session,
    redeem_magic_link,
    request_magic_link,
)
from .errors import (
    ActiveTournamentExistsError,
    AlreadyPlayingHereError,
    AuthError,
    ConflictError,
    DuplicateGroupNameError,
    DuplicatePlayerNameError,
    ForbiddenError,
    GroupNotFoundError,
    InactivePlayerError,
    InvalidTokenError,
    InviteNotFoundError,
    InviteUsedError,
    NotFoundError,
    NotSignedInError,
    PlayerAlreadyClaimedError,
    PlayerNotFoundError,
    PlayerNotInGroupError,
    ServiceError,
    TokenExpiredError,
    TooManyRequestsError,
    TournamentNotFoundError,
)
from .groups import (
    add_player,
    create_group,
    deactivate_player,
    group_for_link,
    groups_for_account,
    link_group,
    list_groups,
    list_players,
    player_for_account,
    rename_player,
)
from .invites import (
    claim_player,
    create_invite,
    peek_invite,
    redeem_invite,
    release_player,
)
from .permissions import (
    ANONYMOUS,
    Anonymous,
    can_organise,
    can_see,
    is_admin,
    is_member,
    require_can_score,
    require_member,
    require_organiser,
    require_owner,
    viewing,
)
from .telegram_auth import account_for_launch
from .tournaments import (
    active_tournament,
    advance_round,
    amend_score,
    count_tournaments,
    extend_tournament,
    finish_tournament,
    get_tournament,
    list_tournaments,
    player_history,
    record_score,
    reroll_tournament,
    start_tournament,
)
from .views import (
    GroupView,
    MatchView,
    PlayerProgress,
    PlayerView,
    ProgressPointView,
    RoundView,
    StandingView,
    TournamentSummary,
    TournamentView,
    View,
    Viewing,
)

__all__ = [
    "ANONYMOUS",
    "ActiveTournamentExistsError",
    "AlreadyPlayingHereError",
    "Anonymous",
    "AuthError",
    "ConflictError",
    "DuplicateGroupNameError",
    "DuplicatePlayerNameError",
    "ForbiddenError",
    "GroupNotFoundError",
    "GroupView",
    "InactivePlayerError",
    "InvalidTokenError",
    "InviteNotFoundError",
    "InviteUsedError",
    "MatchView",
    "NotFoundError",
    "NotSignedInError",
    "PlayerAlreadyClaimedError",
    "PlayerNotFoundError",
    "PlayerNotInGroupError",
    "PlayerProgress",
    "PlayerView",
    "ProgressPointView",
    "RoundView",
    "ServiceError",
    "StandingView",
    "TokenExpiredError",
    "TooManyRequestsError",
    "TournamentNotFoundError",
    "TournamentSummary",
    "TournamentView",
    "View",
    "Viewing",
    "account_for_identity",
    "account_for_launch",
    "account_for_session",
    "active_tournament",
    "add_player",
    "advance_round",
    "amend_score",
    "attach_identity",
    "can_organise",
    "can_see",
    "claim_player",
    "close_all_sessions",
    "close_session",
    "count_tournaments",
    "create_group",
    "create_invite",
    "deactivate_player",
    "ensure_identity",
    "extend_tournament",
    "finish_tournament",
    "get_account",
    "get_tournament",
    "group_for_link",
    "groups_for_account",
    "is_admin",
    "is_member",
    "issue_sign_in_link",
    "link_group",
    "list_groups",
    "list_players",
    "list_tournaments",
    "open_session",
    "peek_invite",
    "player_for_account",
    "player_history",
    "record_score",
    "redeem_invite",
    "redeem_magic_link",
    "release_player",
    "rename_player",
    "request_magic_link",
    "require_can_score",
    "require_member",
    "require_organiser",
    "require_owner",
    "reroll_tournament",
    "start_tournament",
    "viewing",
]
