"""Service layer — the single entry point for every interface.

The CLI, the Telegram bot and the future HTTP API all call these functions. They never talk
to the engine or the database directly, which is what keeps the bot and the web from
drifting apart in the details.

Every function takes a session first and **does not commit**: the caller owns the
transaction, so several calls can be composed into one unit of work.
"""

from .accounts import (
    account_for_identity,
    attach_identity,
    ensure_identity,
    get_account,
)
from .errors import (
    ActiveTournamentExistsError,
    AlreadyPlayingHereError,
    AuthError,
    ConflictError,
    DuplicateGroupNameError,
    DuplicatePlayerNameError,
    ForbiddenError,
    GroupNotFoundError,
    InactivePlayerError,
    InvalidTokenError,
    InviteNotFoundError,
    InviteUsedError,
    NotFoundError,
    PlayerAlreadyClaimedError,
    PlayerNotFoundError,
    PlayerNotInGroupError,
    ServiceError,
    TokenExpiredError,
    TooManyRequestsError,
    TournamentNotFoundError,
)
from .groups import (
    add_player,
    create_group,
    deactivate_player,
    group_for_link,
    link_group,
    list_groups,
    list_players,
    rename_player,
)
from .invites import create_invite, peek_invite, redeem_invite
from .permissions import (
    is_member,
    require_can_score,
    require_member,
    require_organiser,
    require_owner,
)
from .tournaments import (
    active_tournament,
    advance_round,
    amend_score,
    count_tournaments,
    finish_tournament,
    get_tournament,
    list_tournaments,
    player_history,
    record_score,
    reroll_tournament,
    start_tournament,
)
from .views import (
    GroupView,
    MatchView,
    PlayerView,
    RoundView,
    StandingView,
    TournamentSummary,
    TournamentView,
)

__all__ = [
    "ActiveTournamentExistsError",
    "AlreadyPlayingHereError",
    "AuthError",
    "ConflictError",
    "DuplicateGroupNameError",
    "DuplicatePlayerNameError",
    "ForbiddenError",
    "GroupNotFoundError",
    "GroupView",
    "InactivePlayerError",
    "InvalidTokenError",
    "InviteNotFoundError",
    "InviteUsedError",
    "MatchView",
    "NotFoundError",
    "PlayerAlreadyClaimedError",
    "PlayerNotFoundError",
    "PlayerNotInGroupError",
    "PlayerView",
    "RoundView",
    "ServiceError",
    "StandingView",
    "TokenExpiredError",
    "TooManyRequestsError",
    "TournamentNotFoundError",
    "TournamentSummary",
    "TournamentView",
    "account_for_identity",
    "active_tournament",
    "add_player",
    "advance_round",
    "amend_score",
    "attach_identity",
    "count_tournaments",
    "create_group",
    "create_invite",
    "deactivate_player",
    "ensure_identity",
    "finish_tournament",
    "get_account",
    "get_tournament",
    "group_for_link",
    "is_member",
    "link_group",
    "list_groups",
    "list_players",
    "list_tournaments",
    "peek_invite",
    "player_history",
    "record_score",
    "redeem_invite",
    "rename_player",
    "require_can_score",
    "require_member",
    "require_organiser",
    "require_owner",
    "reroll_tournament",
    "start_tournament",
]
