"""Create tournament schema

Revision ID: 436f6478333c
Revises:
Create Date: 2026-08-08 14:31:00.040948
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types are rendered fully qualified by autogenerate, so the module has to be
# importable from every migration.
import padel_tour.db.models

revision: str = "436f6478333c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("telegram_chat_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            padel_tour.db.models.UtcDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("telegram_chat_id"),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            padel_tour.db.models.UtcDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.create_index("uq_players_group_name", ["group_id", "name"], unique=True)

    op.create_table(
        "tournaments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.Column("points_per_match", sa.Integer(), nullable=False),
        sa.Column("pairing_pattern", sa.String(length=20), nullable=False),
        sa.Column("total_rounds", sa.Integer(), nullable=False),
        sa.Column("seed", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            padel_tour.db.models.UtcDateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("finished_at", padel_tour.db.models.UtcDateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rounds",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tournament_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["tournament_id"], ["tournaments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rounds", schema=None) as batch_op:
        batch_op.create_index("uq_round_number", ["tournament_id", "number"], unique=True)

    op.create_table(
        "tournament_players",
        sa.Column("tournament_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("draw_position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["tournament_id"], ["tournaments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tournament_id", "player_id"),
    )
    with op.batch_alter_table("tournament_players", schema=None) as batch_op:
        batch_op.create_index("uq_entry_position", ["tournament_id", "draw_position"], unique=True)

    op.create_table(
        "matches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("round_id", sa.Uuid(), nullable=False),
        sa.Column("court", sa.Integer(), nullable=False),
        sa.Column("team_a1", sa.Uuid(), nullable=False),
        sa.Column("team_a2", sa.Uuid(), nullable=False),
        sa.Column("team_b1", sa.Uuid(), nullable=False),
        sa.Column("team_b2", sa.Uuid(), nullable=False),
        sa.Column("score_a", sa.Integer(), nullable=True),
        sa.Column("score_b", sa.Integer(), nullable=True),
        sa.CheckConstraint("(score_a IS NULL) = (score_b IS NULL)", name="ck_match_score_complete"),
        sa.CheckConstraint(
            "score_a IS NULL OR (score_a >= 0 AND score_b >= 0)", name="ck_match_score_non_negative"
        ),
        sa.ForeignKeyConstraint(["round_id"], ["rounds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.create_index("uq_match_court", ["round_id", "court"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.drop_index("uq_match_court")

    op.drop_table("matches")
    with op.batch_alter_table("tournament_players", schema=None) as batch_op:
        batch_op.drop_index("uq_entry_position")

    op.drop_table("tournament_players")
    with op.batch_alter_table("rounds", schema=None) as batch_op:
        batch_op.drop_index("uq_round_number")

    op.drop_table("rounds")
    op.drop_table("tournaments")
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_index("uq_players_group_name")

    op.drop_table("players")
    op.drop_table("groups")
    # ### end Alembic commands ###
